import AppLayout from "../../../components/AppLayout";

export const metadata = { title: "Privacy Policy" };

const sections: { heading: string; body: string[] }[] = [
  {
    heading: "1. Who we are",
    body: [
      "Calolean (calolean.com) is an AI-powered health assistant for nutrition tracking, food scanning, and exercise form analysis. This policy explains what data we collect, why, and the choices you have. Contact: social@calolean.com.",
    ],
  },
  {
    heading: "2. Data we collect",
    body: [
      "Account data: your email address and display name via Firebase Authentication (email/password or Google sign-in).",
      "Health & fitness data you provide: food logs, calorie/macro goals, age, weight, height, workout logs, water intake, and form-analysis scores. This is stored in your private space in Firebase Firestore (Google Cloud) and is accessible only to your account.",
      "Step data (optional): if you connect Google Health, we read your daily step count with your explicit OAuth consent. You can disconnect at any time, which removes our access.",
      "Usage data: daily AI prompt counts (for fair-use limits) and standard analytics events via Google Analytics.",
    ],
  },
  {
    heading: "3. Photos and videos",
    body: [
      "Food photos are compressed on your device and sent to Google's Gemini AI (via Vertex AI) solely to identify the food and estimate nutrition. We do not store your photos.",
      "Workout videos NEVER leave your device. Pose detection runs locally in your browser; only an anonymized joint-angle summary (numbers, no images) is sent to our AI for form scoring.",
    ],
  },
  {
    heading: "4. AI processing",
    body: [
      "Food analysis, chat answers, and form scoring are generated by Google Gemini models running on Google Cloud Vertex AI. AI outputs are estimates and ratings for informational purposes — they are not medical advice. Always consult a professional for medical or dietary conditions.",
    ],
  },
  {
    heading: "5. Advertising & affiliate links",
    body: [
      "Free accounts see clearly labeled 'Sponsored' ad cards served by Google AdSense. Ad context comes only from generic food/fitness category keywords (e.g. 'high protein') — never your chat text, photos, or personal data.",
      "In the EEA/UK we show a consent banner (Google's certified CMP) before any advertising cookies are set. You can decline personalised ads.",
      "Some product suggestions contain Amazon affiliate links, marked with an external-link icon. We may earn a commission at no extra cost to you.",
    ],
  },
  {
    heading: "6. Data sharing",
    body: [
      "We do not sell your personal data. Data is processed by our infrastructure providers: Google (Firebase, Cloud SQL, Vertex AI, Analytics, AdSense) and Vercel (hosting). Nutrition lookups may query the public USDA FoodData Central and Open Food Facts databases using the food name only.",
    ],
  },
  {
    heading: "7. Retention & your rights",
    body: [
      "Your data is retained while your account is active. You can export everything as CSV (Profile → Export Data) and delete your account (Profile → Delete Account) at any time; deletion removes access to your stored logs.",
      "Depending on your region (GDPR, CCPA, DPDP), you have rights of access, rectification, erasure, and portability. Email social@calolean.com to exercise them.",
    ],
  },
  {
    heading: "8. Security",
    body: [
      "Data is encrypted in transit (TLS) and at rest in Google Cloud. Firestore security rules restrict each user's data to their own account. Google Health refresh tokens are additionally encrypted at the application layer (AES-256-GCM).",
    ],
  },
  {
    heading: "9. Children",
    body: ["Calolean is not intended for children under 13 (or the minimum age in your country) and we do not knowingly collect their data."],
  },
  {
    heading: "10. Changes",
    body: ["We will post any changes to this policy here and update the date below. Last updated: June 2026."],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <AppLayout>
      <div className="p-6 lg:p-8 max-w-3xl">
        <div className="cl-card-elevated" style={{ borderRadius: 24, padding: 28 }}>
          <h1 style={{ fontSize: 24, fontWeight: 700, color: "var(--text-primary)", marginBottom: 18 }}>Privacy Policy</h1>
          <div className="space-y-6">
            {sections.map((section) => (
              <section key={section.heading}>
                <h2 style={{ fontSize: 15, fontWeight: 700, color: "var(--text-primary)", marginBottom: 8 }}>
                  {section.heading}
                </h2>
                {section.body.map((paragraph, index) => (
                  <p key={index} style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.7, marginBottom: 8 }}>
                    {paragraph}
                  </p>
                ))}
              </section>
            ))}
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
